language: python
python:
- "3.8"
env:
- DJANGO=2.0 DB=sqlite3

global:
  - PGPORT=5432

install:
#- pip install -r requirements.txt , Se comenta esta línea a esperas de generar un requirements.txt correcto
- pip install coverage
- pip install codacy-coverage

script:
- cd groomeet_backend
- coverage run --branch --source=. ./manage.py test --keepdb
- coverage xml
- python-codacy-coverage -r coverage.xml

branches:
   only:
     - main


