# Generated by Django 3.1.2 on 2021-03-20 11:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Banda',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('is_removed', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Genero',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Instrumento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Musico',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fechaNacimiento', models.DateField(null=True, verbose_name='Fecha de nacimiento')),
                ('generos', models.ManyToManyField(to='groomeet_backend.Genero')),
                ('instrumentos', models.ManyToManyField(to='groomeet_backend.Instrumento')),
                ('likesRecibidos', models.ManyToManyField(blank=True, related_name='likesDados', to=settings.AUTH_USER_MODEL)),
                ('noLikesRecibidos', models.ManyToManyField(blank=True, related_name='noLikesDados', to=settings.AUTH_USER_MODEL)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MiembroDe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fechaUnion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de unión')),
                ('banda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='groomeet_backend.banda')),
                ('musico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='groomeet_backend.musico')),
            ],
        ),
        migrations.CreateModel(
            name='Mensaje',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('is_removed', models.BooleanField(default=False)),
                ('cuerpo', models.TextField(verbose_name='Cuerpo del mensaje')),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mensajes', to='groomeet_backend.musico', verbose_name='Autor')),
                ('chat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mensajes', to='groomeet_backend.chat', verbose_name='Chat')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Invitacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('estado', models.BooleanField(default=False)),
                ('emisor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invitacionesEnviadas', to='groomeet_backend.musico')),
                ('receptor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invitacionesRecibidas', to='groomeet_backend.musico')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='chat',
            name='participante1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chats1', to='groomeet_backend.musico', verbose_name='Participante 1'),
        ),
        migrations.AddField(
            model_name='chat',
            name='participante2',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chats2', to='groomeet_backend.musico', verbose_name='Participante 2'),
        ),
        migrations.AddField(
            model_name='banda',
            name='administrador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='bandasAdministradas', to='groomeet_backend.musico'),
        ),
        migrations.AddField(
            model_name='banda',
            name='miembros',
            field=models.ManyToManyField(through='groomeet_backend.MiembroDe', to='groomeet_backend.Musico'),
        ),
    ]
