# Generated by Django 3.1.7 on 2021-04-05 20:38

from django.db import migrations, models
import groomeet_backend.models


class Migration(migrations.Migration):

    dependencies = [
        ('groomeet_backend', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invitacion',
            name='estado',
            field=models.CharField(choices=[(groomeet_backend.models.EstadoInvitacion['Rechazada'], 'Rechazada'), (groomeet_backend.models.EstadoInvitacion['Pendiente'], 'Pendiente'), (groomeet_backend.models.EstadoInvitacion['Aceptada'], 'Aceptada')], max_length=40),
        ),
    ]
