# Generated by Django 3.1.3 on 2021-04-02 14:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import groomeet_backend.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('groomeet_backend', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='banda',
            name='generos',
            field=models.ManyToManyField(blank=True, to='groomeet_backend.Genero'),
        ),
        migrations.AddField(
            model_name='banda',
            name='instrumentos',
            field=models.ManyToManyField(blank=True, to='groomeet_backend.Instrumento'),
        ),
        migrations.AddField(
            model_name='banda',
            name='likesRecibidosBanda',
            field=models.ManyToManyField(blank=True, related_name='likesDadosBanda', to='groomeet_backend.Banda'),
        ),
        migrations.AddField(
            model_name='banda',
            name='likesRecibidosMusico',
            field=models.ManyToManyField(blank=True, related_name='likesDadosBanda', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='banda',
            name='noLikesRecibidosBanda',
            field=models.ManyToManyField(blank=True, related_name='noLikesDadosBanda', to='groomeet_backend.Banda'),
        ),
        migrations.AddField(
            model_name='banda',
            name='noLikesRecibidosMusico',
            field=models.ManyToManyField(blank=True, related_name='noLikesDadosBanda', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='instrumento',
            name='familia',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='invitacion',
            name='banda',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='groomeet_backend.banda'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='musico',
            name='likesRecibidosBanda',
            field=models.ManyToManyField(blank=True, related_name='likesDadosMusico', to='groomeet_backend.Banda'),
        ),
        migrations.AddField(
            model_name='musico',
            name='noLikesRecibidosBanda',
            field=models.ManyToManyField(blank=True, related_name='noLikesDadosMusico', to='groomeet_backend.Banda'),
        ),
        migrations.AlterField(
            model_name='banda',
            name='miembros',
            field=models.ManyToManyField(blank=True, through='groomeet_backend.MiembroDe', to='groomeet_backend.Musico'),
        ),
        migrations.AlterField(
            model_name='genero',
            name='nombre',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='instrumento',
            name='nombre',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='invitacion',
            name='estado',
            field=models.CharField(choices=[(groomeet_backend.models.EstadoInvitacion['Rechazada'], 'Rechazada'), (groomeet_backend.models.EstadoInvitacion['Pendiente'], 'Pendiente'), (groomeet_backend.models.EstadoInvitacion['Aceptada'], 'Aceptada')], max_length=9),
        ),
        migrations.CreateModel(
            name='MiembroNoRegistrado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=500)),
                ('descripcion', models.CharField(max_length=500)),
                ('banda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='miembrosNoRegistrados', to='groomeet_backend.banda')),
                ('instrumentos', models.ManyToManyField(blank=True, to='groomeet_backend.Instrumento')),
            ],
        ),
    ]
