# Generated by Django 3.1.7 on 2021-04-17 15:42

from django.db import migrations, models
import groomeet_backend.models


class Migration(migrations.Migration):

    dependencies = [
        ('groomeet_backend', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='musico',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to=groomeet_backend.models.rename_avatar_image),
        ),
        migrations.AddField(
            model_name='musico',
            name='descripcion',
            field=models.TextField(null=True, verbose_name='Descripción'),
        ),
        migrations.AddField(
            model_name='musico',
            name='enlaceVideo',
            field=models.CharField(blank=True, max_length=150, verbose_name='Enlace de vídeo'),
        ),
        migrations.AlterField(
            model_name='musico',
            name='generos',
            field=models.ManyToManyField(to='groomeet_backend.Genero', verbose_name='Géneros'),
        ),
    ]
