# Generated by Django 3.1.2 on 2021-03-20 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groomeet_backend', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='genero',
            name='nombre',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='instrumento',
            name='nombre',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
