# Generated by Django 3.1.2 on 2021-03-19 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groomeet_backend', '0002_auto_20210319_1300'),
    ]

    operations = [
        migrations.AlterField(
            model_name='musico',
            name='fechaNacimiento',
            field=models.DateField(null=True, verbose_name='Fecha de nacimiento'),
        ),
    ]
