# Generated by Django 3.1.3 on 2021-03-26 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groomeet_backend', '0002_auto_20210320_1345'),
    ]

    operations = [
        migrations.AddField(
            model_name='instrumento',
            name='familia',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
