# Generated by Django 3.1.7 on 2021-05-02 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groomeet_backend', '0002_auto_20210428_1957'),
    ]

    operations = [
        migrations.CreateModel(
            name='Anuncio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.TextField()),
                ('imagen', models.URLField(verbose_name='Enlace de vídeo')),
                ('destino', models.URLField(verbose_name='Enlace de vídeo')),
            ],
        ),
    ]
