# Generated by Django 3.1.7 on 2021-04-18 16:14

import datetime
from django.db import migrations, models
import groomeet_backend.models


class Migration(migrations.Migration):

    dependencies = [
        ('groomeet_backend', '0002_auto_20210417_1542'),
    ]

    operations = [
        migrations.AddField(
            model_name='banda',
            name='descripcion',
            field=models.TextField(null=True, verbose_name='Descripción'),
        ),
        migrations.AddField(
            model_name='banda',
            name='enlaceVideo',
            field=models.URLField(blank=True, verbose_name='Enlace de vídeo'),
        ),
        migrations.AddField(
            model_name='banda',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to=groomeet_backend.models.rename_image_banda, verbose_name='Imagen de la banda'),
        ),
        migrations.AddField(
            model_name='musico',
            name='isBoosted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='musico',
            name='likesDisponibles',
            field=models.IntegerField(default=10),
        ),
        migrations.AddField(
            model_name='musico',
            name='superLikes',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='musico',
            name='ultimaRenovacionLikes',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='musico',
            name='enlaceVideo',
            field=models.URLField(blank=True, verbose_name='Enlace de vídeo'),
        ),
    ]
