# Generated by Django 3.1.7 on 2021-04-14 15:56

from django.db import migrations, models
import django.utils.timezone
import groomeet_backend.models


class Migration(migrations.Migration):

    dependencies = [
        ('groomeet_backend', '0002_auto_20210408_1019'),
    ]

    operations = [
        migrations.AddField(
            model_name='musico',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to=groomeet_backend.models.rename_avatar_image),
        ),
        migrations.AddField(
            model_name='musico',
            name='descripcion',
            field=models.TextField(default=django.utils.timezone.now, verbose_name='Descripción'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='musico',
            name='enlaceVideo',
            field=models.URLField(blank=True, verbose_name='Enlace de vídeo'),
        ),
        migrations.AlterField(
            model_name='musico',
            name='generos',
            field=models.ManyToManyField(to='groomeet_backend.Genero', verbose_name='Géneros'),
        ),
    ]
