# Generated by Django 3.1.7 on 2021-03-26 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groomeet_backend', '0003_banda_miembrosnoregistrados'),
    ]

    operations = [
        migrations.AddField(
            model_name='banda',
            name='generos',
            field=models.ManyToManyField(blank=True, to='groomeet_backend.Genero'),
        ),
        migrations.AddField(
            model_name='banda',
            name='instrumentos',
            field=models.ManyToManyField(blank=True, to='groomeet_backend.Instrumento'),
        ),
        migrations.AlterField(
            model_name='banda',
            name='miembros',
            field=models.ManyToManyField(blank=True, through='groomeet_backend.MiembroDe', to='groomeet_backend.Musico'),
        ),
    ]
