# Generated by Django 3.1.3 on 2021-03-31 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groomeet_backend', '0003_instrumento_familia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instrumento',
            name='familia',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
