# Generated by Django 3.1.7 on 2021-03-26 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groomeet_backend', '0004_auto_20210326_1109'),
    ]

    operations = [
        migrations.AddField(
            model_name='instrumento',
            name='familia',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
