# Generated by Django 3.1.7 on 2021-03-26 12:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('groomeet_backend', '0005_instrumento_familia'),
    ]

    operations = [
        migrations.CreateModel(
            name='MiembroNoRegistrado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=500)),
                ('descripcion', models.CharField(max_length=500)),
                ('banda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='groomeet_backend.banda')),
                ('instrumentos', models.ManyToManyField(blank=True, to='groomeet_backend.Instrumento')),
            ],
        ),
    ]
