# Generated by Django 3.1.7 on 2021-03-26 12:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('groomeet_backend', '0006_miembronoregistrado'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='banda',
            name='miembrosNoRegistrados',
        ),
        migrations.AlterField(
            model_name='miembronoregistrado',
            name='banda',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='miembrosNoRegistrados', to='groomeet_backend.banda'),
        ),
    ]
