# Generated by Django 3.1.7 on 2021-03-27 10:30

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('groomeet_backend', '0007_auto_20210326_1219'),
    ]

    operations = [
        migrations.AddField(
            model_name='banda',
            name='likesRecibidosBanda',
            field=models.ManyToManyField(blank=True, related_name='likesDadosBanda', to='groomeet_backend.Banda'),
        ),
        migrations.AddField(
            model_name='banda',
            name='likesRecibidosMusico',
            field=models.ManyToManyField(blank=True, related_name='likesDadosBanda', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='banda',
            name='noLikesRecibidosBanda',
            field=models.ManyToManyField(blank=True, related_name='noLikesDadosBanda', to='groomeet_backend.Banda'),
        ),
        migrations.AddField(
            model_name='banda',
            name='noLikesRecibidosMusico',
            field=models.ManyToManyField(blank=True, related_name='noLikesDadosBanda', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='musico',
            name='likesRecibidosBanda',
            field=models.ManyToManyField(blank=True, related_name='likesDadosMusico', to='groomeet_backend.Banda'),
        ),
        migrations.AddField(
            model_name='musico',
            name='noLikesRecibidosBanda',
            field=models.ManyToManyField(blank=True, related_name='noLikesDadosMusico', to='groomeet_backend.Banda'),
        ),
    ]
